### ISSUE TITLE
Continuous integration with Travis CI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-web-ui#8]
### Description
Integrate Travis CI for the Quality Control with Unit Tests and Linting.

### Expected behaviour
Pass all tests in every push of master and develop branches and PRs.

### Actual behaviour
Fail without bower.

### References

- https://travis-ci.org/flyve-mdm/flyve-mdm-web-ui
- https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by ajsb85** [comment]
Try @CircleCI  https://circleci.com/

**Comment by ajsb85** [comment]
The simple build config works at the first time. 👌 

```YML
language: node_js
node_js:
  - "7"
install:
  - gem install compass
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - npm install -g grunt
script: grunt build
notifications:
  email: false
```

![image](https://cloud.githubusercontent.com/assets/663460/23032808/0e725eb4-f476-11e6-9858-6cf899d39a8a.png)
