### ISSUE TITLE
CHANGELOG for gh-pages

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-web-ui#97]
Hi, @ajsb85 

It is necessary that at the moment of generating a new changelog this one is sent to the branch gh-pages so that it can be always updated in the project site. For it to deploy correctly it is mandatory that you have a Jekyll yaml header that has the following appearance:

```yaml
---
layout: modal
title: changelog
---
```
Thanks in advance.
